GET http://localhost:5000/habits


###
GET http://localhost:5000/habits/65a3ad9d8f8bf5fb6b6b7a72


###
POST http://localhost:5000/habits
content-type: application/json

{
  "settings": {
    "title": "Jinal (DONT DELETE DUMBASS)",
    "type": "bool",
    "colour": "#fff473"
  }
}

###
DELETE http://localhost:5000/habits/65a3b62db18868105c5ed659

###
PATCH http://localhost:5000/habits/65a3a832aeab467e224eeac2
content-type: application/json

{
    "title": "Gym changed 🦾",
    "colour": "#DA6F58"
}

###
PATCH http://localhost:5000/habits/65a3b8e427d56984ee8ab333/addEntry
content-type: application/json

{
  "day": 4,
  "value": "8"
}