GET http://localhost:5000/habits


###
GET http://localhost:5000/habits/65a39eece622409143fbe75e


###
POST http://localhost:5000/habits
content-type: application/json

{
  "settings": {
    "title": "Gym 🦾",
    "type": "bool",
    "colour": "#fff473"
  },
  "entries": [
    {
      "day": 1,
      "value": "1"
    },
    {
        "day": 1,
        "value": "1"
    }
  ]
}

###
DELETE http://localhost:5000/habits/65a39ea0e622409143fbe756

###
PATCH http://localhost:5000/habits/65a3a832aeab467e224eeac2
content-type: application/json

{
    "title": "Gym changed 🦾",
    "colour": "#DA6F58"
}