GET http://localhost:5000/habits


###
POST http://localhost:5000/habits
content-type: application/json

{
  "settings": {
    "title": "Gym 🦾",
    "type": "bool",
    "colour": "fff473"
  },
  "entries": [
    {
      "day": 1,
      "value": "1"
    },
    {
        "day": 1,
        "value": "1"
    }
  ]
}

###
PATCH http://localhost:5000/habits/update
content-type: application/json

{
    "title": "Gym 🦾",
    "colour": "testChange"
}